export default {
  DEFAULT_LOOT_SHEET: "",
  DEFAULT_SPELL_COMPENDIUM: "",
  QUANTITY_PROPERTY_PATH: "",
  PRICE_PROPERTY_PATH: "",
  SPELL_LEVEL_PATH: "",
  ITEM_LOOT_TYPE: "",
  SCROLL_REGEX: "",
};
